### PR TITLE
Group kind matchers by apiGroup

### LINKED ISSUE #269: Unexpected match.kinds generated when matching multiple apiGroups
I expect `@kinds` matchers to produce `spec.match.kinds` combined by apiGroups, instead of producing single `kinds` matcher for all apiGroups and all kinds.

For example, I expect this annotation:
```rego
# @kinds core/Pod apps/Deployment
```

To produce following `spec.match.kinds`:
```yaml
kinds:
- apiGroups:
  - ""
  kinds:
  - Pod
- apiGroups:
  - apps
  kinds:
  - Deployment
```

instead of currently generated:
```yaml
- apiGroups:
  - ""
  - apps
  kinds:
  - Pod
  - Deployment
```

### PR DESCRIPTION
**Pull request by stek29**
Fixes #269

I've also added sorting into kinds matcher generation so it always produces consistent result for given set of `@kinds` matchers.

If that's undesirable/unneeded, I can remove sorting in each apiGroup or even remove sorting completely, so results are produced in order of given annotations – please ping me if that's the case.

### CODE REVIEW

**Review by jalseth — CHANGES_REQUESTED** [review]
Thanks for the PR! I think it would make more sense to implement these changes in the [matchers parsing](https://github.com/plexsystems/konstraint/blob/main/internal/rego/matchers.go) than only right before we render the YAML.

**Comment by stek29** [comment]
@jalseth done

**Review by jalseth — APPROVED** [review]
The changes LGTM! It looks like the acceptance tests are now failing which is expected because this changes the generated `Constraint` files. Please fix the acceptance tests and squash these commits into one and I can merge.

**Comment by stek29** [comment]
@jalseth done

**Comment by jalseth** [comment]
:shipit: thanks again!

**Pull request merged**
