### PR TITLE
Updated rego file load to be sorted via path

### PR DESCRIPTION
**Pull request by garethahealy**
Attempts to solve: https://github.com/plexsystems/konstraint/pull/20#issuecomment-662272822

_Disclaimer_: still learning golang. had a google to see if there was an ordered map in go, but google suggested not.

### CODE REVIEW

**Comment by jpreese** [comment]
Thanks for pointing this out, and taking a shot at it @garethahealy! Glad you're learning Go, always exciting to see new comers to the language :)

For the sorting piece, we shouldn't need the `map`, but rather you could use [sort.Slice](https://golang.org/pkg/sort/#Slice)

Something like (did not try and compile)! 

```golang
sort.Slice(regoFiles, func(i, j) bool {
  return regoFiles[i].FilePath < regoFiles[j]
}
```

**Comment by garethahealy** [comment]
@jpreese ; updated as suggested.

**Comment by jpreese** [comment]
Awesome. Perfect!

**Comment by jpreese** [comment]
🎉

**Pull request merged**
