### PR TITLE
Split k8s library

### PR DESCRIPTION
**Pull request by jalseth**
This splits the large k8s library into multiple smaller ones. This is just a starting point, the libraries can be improved over time.

It also adds a check to ensure we are adding the correct number of libraries to a given ConstraintTemplate so we don't accidentally send Gatekeeper invalid resources.

Edit: Addresses #9

### CODE REVIEW

**Comment by jalseth** [comment]
Weird. The tests pass locally for me. I'll look into it more later.

**Comment by jpreese** [comment]
Woo! This is awesome. For an initial merge, my stance is that if it works, I'm OK with it. I have a couple thoughts-- but they might be better served in future PRs to limit the Christmas celebration that's already going on.

1. I think we could get rid of `split_images` in `workloads.rego`. That function came from https://github.com/instrumenta/policies/tree/master/kubernetes (as well as a decent chunk of the other functions. couldn't get any movement on maintainership there).

Its only use is to see if a container has a latest tag, but we just use the Rego primitive `ends_with` to do that.

2. I'm on the fence about `container_images` (in workloads.rego). This is the same as `containers[_].image`. It feels a little odd to call out this property specifically. Looking through our policies in house, we just use `.image`.

Since these rules get copied into each policy, I would err on the side of cutting ruthlessly if we're sure it doesn't provide a lot of value. Move more policy-specific rules to the policy themselves.

**Comment by jalseth** [comment]
@jpreese Agreed, I pulled those functions out. I'm debating the value of the `security` package, but I think we can merge this and improve these as time goes along.

**Comment by jpreese** [comment]
+1 we'll iterate as things pop up. Templates look much smaller! :tada:

**Pull request merged**
