### PR TITLE
Allow specifying namespaces and excludedNamespaces in Constraint match criteria

### PR DESCRIPTION
**Pull request by jalseth**
This adds flags for specifying the `namespaces` and `excludedNamespaces` in the Constraint `match` criteria.

### CODE REVIEW

**Comment by jalseth** [comment]
@jpreese I think this is ready.

**Comment by jpreese** [comment]
Thanks for the PR @jalseth. 

What are your thoughts on driving the `match` criteria from the Rego as well? It's an idea that I'm playing around with, but I am unsure if it makes sense for how other teams interact with Gatekeeper. For me, I'd love to keep as much parity with `Conftest` as possible. 

For example, lets say you have the following policy from the README:

```rego
# Container images can not use the latest tag.
# @Kinds apps/DaemonSet apps/Deployment apps/StatefulSet core/Pod
violation[msg] {
  has_latest_tag

  msg := k8s.format(sprintf("(%s) %s: Images must not use the latest tag", [k8s.kind, k8s.name]))
}

has_latest_tag {
  endswith(k8s.container_images[_], ":latest")
}
```

This policy would apply to all resources, regardless of namespace (minus as exclusions you have set in the Gatekeeper configuration itself).

But if you wanted a policy to not apply to the `monitoring` namespace you could do:

```rego
# Container images can not use the latest tag.
# @Kinds apps/DaemonSet apps/Deployment apps/StatefulSet core/Pod
# @ExcludeNamespaces monitoring
violation[msg] {
  not k8s.namespace == "monitoring"
  has_latest_tag

  msg := k8s.format(sprintf("(%s) %s: Images must not use the latest tag", [k8s.kind, k8s.name]))
}

has_latest_tag {
  endswith(k8s.container_images[_], ":latest")
}
```

Then `Conftest` would know that a Kubernetes manifest that includes the `latest` tag is actually OK inside of the monitoring namespace.

My primary concern with controlling exclusions/specific namespaces via flags is you might lose what truly is/is not allowed when executing the policy against Conftest.

That said, as briefly mentioned, Gatekeeper does allow you to ignore certain namespaces. Do you have a use case where resources are created in a Namespace that Gatekeeper watches, but you want to exclude some policies? Could you turn off Gatekeepers enforcement for the entire namespace?

**Comment by jalseth** [comment]
The goal for having these exposed as flags is to enable teams to pull policies from a central repository and then tweak them as needed for their clusters in automated deployment flows. If we have the included/excluded namespaces in the policies themselves, teams likely have to maintain their own forks of the policies if they need to change the target namespaces, which would lead to policy drift. By allowing these flags to be set in the generator, it would be easy for the deployment pipeline to specify target namespaces as needed.

I see the benefits of both options, and agree that keeping the full scope of the policy that Conftest and Gatekeeper evaluate as similar as possible to avoid any surprises at deployment time. I am not using this flow at the moment, so I will close this PR so we don't have additional code to refactor as this evolves.

**Comment by jpreese** [comment]
Valid point. If/when the use case does appear, let's continue the discussion.

**Pull request closed without merging**
