### PR TITLE
Add metadata to core library

### PR DESCRIPTION
**Pull request by jpreese**
While converting existing policies to use the new lib layout, writing policies against `labels` seemed a little out of place. This adds a `metadata` property, so `core.metadata` is valid. This is consistent with apiversion/kind. 

`name` is admittedly slightly out of place, but it's probably used enough to warrant the exception.

edit: For consistency with the other fields, should api_version be changed to apiVersion? We don't use this in any of our policies yet, but seems good to have.

### CODE REVIEW

**Comment by jpreese** [comment]
After some additional work with the new library, I also ended up adding `spec`. This should be the last core field as it now includes ever base field a resource can have (apiversion, kind, metadata, spec)

**Comment by jalseth** [comment]
I am for updating the policy to use the core library, but I am against adding the `spec` and `metadata` fields. I don't think creating a global variable that refers to an object makes a ton of sense because either way, you're going to be typing `core.metadata.XYZ` in a policy rule to access its sub-values which to me isn't any different or easier than `core.object.metadata.XYZ`. Additionally, some Kubernetes resources like `Deployment`s have nested `spec` fields so it can make it unclear which part of the resource it is actually referring to.

**Comment by jpreese** [comment]
I do like having `core.kind` , `core.apiVersion` , etc that refer to the root level Kubernetes fields. I think of this as the "entry point". Anything after that is a direct mapping to the resource itself.

So in the example of Deployment having multiple specs, that would just be:
`core.spec.templates.spec`

In this instance, what was _really_ tripping me up was the inconsistency. For example, to access `kind` we do `core.kind`, to access `apiVersion` we do `core.apiVersion` -- but to access `metadata` we're doing `core.object.metadata`. As a user of this library, it felt right to type `core.metadata`.

That all said, while I do like not having to type `object` and writing `core.kind/spec/etc` feels more natural I am OK with introducing `.object` it if we remove the other ones as well (kind, apiVersion).

**Comment by jalseth** [comment]
Perhaps we're writing our policies different then. I tend to write along the lines of
```rego
containers[container]
container.XYZ = "abc"
```

or 

```rego
psps[psp]
psp.spec.privileged
```

I rarely go through the `core.object.X` tree since virtually everything I want is under the workload or podsecuritypolicy spec. The only metadata I currently care about are the kind and name, although labels and annotations will be useful to me (and I believe others) as well in the future, so exposing those into `core.labels` and `core.annotations` would make sense to me. I'm trying to keep these libraries as small as possible and only adding to them items I believe will be accessed and used frequently, otherwise for that one-off policy it's just easier to write the `object.metadata.XYZ` rule in that fashion.

**Comment by jpreese** [comment]
Rename `object` -> `resource`

Exposing:
- apiVersion
- kind
- name
- labels

**Comment by jalseth** [comment]
@jpreese Sorry for the force push, I messed up the rebase after merging #32. It should be fine now, feel free to merge after confirming it looks good to you.

**Comment by jpreese** [comment]
@jalseth no problemo-- LGTM 🎉 . See you just approved it, merging now.

**Pull request merged**
